# Generated by Django 4.2.8 on 2024-12-18 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoreporte',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta'),
        ),
    ]
