# Generated by Django 4.2.8 on 2024-12-18 22:13

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import facturacion.models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('core', '0006_alter_producto_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RegistroTurnos', '0001_initial'),
        ('facturacion', '0002_impuesto_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='La identificación debe tener 10 dígitos (cédula) o 13 dígitos (RUC).', regex='^\\d{10}|\\d{13}$')])),
                ('tipo_identificacion', models.CharField(choices=[('04', 'RUC'), ('05', 'Cédula'), ('06', 'Pasaporte'), ('07', 'Consumidor Final')], max_length=2)),
                ('razon_social', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('obligado_contabilidad', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('numero_autorizacion', models.CharField(max_length=49, unique=True)),
                ('clave_acceso', models.CharField(blank=True, max_length=49, null=True, unique=True)),
                ('tipo_comprobante', models.CharField(choices=[('01', 'Factura'), ('03', 'Liquidación de compra de bienes y prestación de servicios'), ('04', 'Nota de crédito'), ('05', 'Nota de débito'), ('06', 'Guía de remisión'), ('07', 'Comprobante de retención')], default='01', max_length=2)),
                ('contribuyente_especial', models.CharField(blank=True, max_length=5, null=True)),
                ('obligado_contabilidad', models.BooleanField(default=False)),
                ('moneda', models.CharField(default='DOLAR', max_length=10)),
                ('total_sin_impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_con_impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('EN_PROCESO', 'En Proceso'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada')], default='EN_PROCESO', max_length=20)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO_PARCIAL', 'Pagado Parcialmente'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20)),
                ('valor_iva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to=facturacion.models.ruta_factura)),
                ('es_cotizacion', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('registroturno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RegistroTurnos.registroturno')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('sucursal', 'numero_autorizacion')},
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_sri', models.CharField(choices=[('01', 'Sin utilización del sistema financiero'), ('15', 'Compensación de deudas'), ('16', 'Tarjeta de débito'), ('17', 'Dinero electrónico'), ('18', 'Tarjeta prepago'), ('19', 'Tarjeta de crédito'), ('20', 'Otros con utilización del sistema financiero'), ('21', 'Endoso de títulos')], default='01', help_text='Código del método de pago según el SRI', max_length=2)),
                ('descripcion', models.CharField(default='Sin descripción', help_text='Descripción del método de pago', max_length=100)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Monto total del pago', max_digits=10)),
                ('plazo', models.IntegerField(blank=True, default=0, help_text='Plazo de pago en días, si aplica', null=True)),
                ('unidad_tiempo', models.CharField(blank=True, default='días', help_text='Unidad de tiempo para el plazo, ej. días, meses', max_length=20, null=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.factura')),
            ],
        ),
    ]
