# Generated by Django 4.2.8 on 2024-12-10 06:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('nombre_comercial', models.CharField(max_length=255, verbose_name='Nombre Comercial')),
                ('razon_social', models.CharField(max_length=255, unique=True, verbose_name='Razón Social')),
                ('ruc', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El RUC debe tener exactamente 13 dígitos numéricos.', regex='^\\d{13}$')], verbose_name='RUC')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('obligado_contabilidad', models.BooleanField(default=False, verbose_name='Obligado a llevar contabilidad')),
                ('tipo_contribuyente', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Contribuyente')),
                ('representante_legal', models.CharField(blank=True, max_length=255, verbose_name='Representante Legal')),
                ('actividad_economica', models.CharField(blank=True, max_length=255, verbose_name='Actividad Económica')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='empresas.empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
