# Generated by Django 4.2.8 on 2025-01-21 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresas", "0001_initial"),
        ("compras", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="empresa",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="empresas.empresa",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="compra",
            constraint=models.UniqueConstraint(
                fields=("sucursal", "fecha_emision"),
                name="unique_sucursal_fecha_emision",
            ),
        ),
    ]
