# Generated by Django 4.2.8 on 2024-12-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sucursal',
            index=models.Index(fields=['empresa'], name='core_sucurs_empresa_2f4cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='sucursal',
            index=models.Index(fields=['codigo_establecimiento', 'punto_emision'], name='core_sucurs_codigo__0fbac6_idx'),
        ),
    ]
