# Generated by Django 4.2.8 on 2024-12-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('core', '0004_alter_sucursal_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='empresa',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='empresas.empresa'),
        ),
    ]
